export const PROFILE_CAMPAIGN_DARK_COLOR = '#FFFFFF';
export const PROFILE_CAMPAIGN_LIGHT_COLOR = '#31007a';
export const PROFILE_CAMPAIGN_FLASHY_APY_COLOR = '#653ba3';
export const PROFILE_CAMPAIGN_DARK_TOKEN = `${process.env.NEXT_PUBLIC_STRAPI_URL}/uploads/Sei_Symbol_Gradient_ea276889b3.png`;
export const PROFILE_CAMPAIGN_LIGHT_TOKEN = `${process.env.NEXT_PUBLIC_STRAPI_URL}/uploads/Sei_Symbol_Gradient_ea276889b3.png`;
export const PROFILE_CAMPAIGN_DARK_CHAIN = `${process.env.NEXT_PUBLIC_STRAPI_URL}/uploads/Sei_Symbol_Gradient_ea276889b3.png`;
export const PROFILE_CAMPAIGN_LIGHT_CHAIN = `${process.env.NEXT_PUBLIC_STRAPI_URL}/uploads/Sei_Symbol_Gradient_ea276889b3.png`;
export const REWARDS_CHAIN_IDS = ['1135', '30', '8453', '80094'];
export const MERKL_CREATOR_TAG = 'jumper-test';
