export enum TrackingCategories {
  Language = 'language',
  Menu = 'menu',
  Navigation = 'navigation',
  Wallet = 'wallet',
  WalletSelectMenu = 'wallet-select-menu',
  SupportModal = 'support-modal',
  ThemeMenu = 'theme-menu',
  ThemeSwitch = 'theme-switch',
  WidgetEvent = 'widget-event',
}

export enum TrackingActions {
  AddChain = 'add-chain',
  AddToken = 'add-token',
  ClickThemeSwitch = 'click-theme-switch',
  SelectWallet = 'select-wallet',
  ConnectWallet = 'connect-wallet',
  Disconnect = 'disconnect',
  OnRouteExecutionStarted = 'onRouteExecutionStarted',
  OnRouteExecutionCompleted = 'onRouteExecutionCompleted',
  OnRouteExecutionFailed = 'onRouteExecutionFailed',
  OnRouteExecutionUpdated = 'onRouteExecutionUpdated',
  OnRouteHighValueLoss = 'onRouteHighValueLoss',
  OpenWalletMenu = 'open-wallet-menu',
  OpenSubmenu = 'open-submenu',
  OpenSupportModal = 'open-support-modal',
  OpenWalletSelectMenu = 'open-wallet-select-menu',
  SwitchChain = 'switch-chain',
  SwitchLanguage = 'switch-language',
  SwitchTab = 'switch-tab',
  SwitchThemeMode = 'switch-theme-mode',
}
