export const ENABLE_ETHERSPOT_KLIMA_SHOWCASE =
  process.env.REACT_APP_ENABLE_ETHERSPOT_KLIMA === 'true'
export const REACT_APP_ENABLE_OFFSET_CARBON_SHOWCASE =
  process.env.REACT_APP_ENABLE_OFFSET_CARBON === 'true'
export const REACT_APP_ENABLE_SWAP_V2 = process.env.REACT_APP_ENABLE_SWAP_V2 === 'true'
export const REACT_APP_ENABLE_CLAIMING = process.env.REACT_APP_ENABLE_CLAIMING === 'true'
