export const ENABLE_ETHERSPOT_KLIMA_SHOWCASE =
  process.env.REACT_APP_ENABLE_ETHERSPOT_KLIMA === 'true'
export const REACT_APP_ENABLE_OFFSET_CARBON_SHOWCASE =
  process.env.REACT_APP_ENABLE_OFFSET_CARBON === 'true'
