export const ENABLE_KLIMA_STAKE_SHOWCASE =
  process.env.REACT_APP_ENABLE_KLIMA_STAKE_SHOWCASE === 'true'
export const REACT_APP_ENABLE_OFFSET_CARBON_SHOWCASE =
  process.env.REACT_APP_ENABLE_OFFSET_CARBON === 'true'
export const REACT_APP_ENABLE_CLAIMING = process.env.REACT_APP_ENABLE_CLAIMING === 'true'
