import type { BlogArticleData } from '@/types/strapi';

export const blogArticle: BlogArticleData = {
  id: 60311,
  documentId: 'ddyucbrrm3d7t2toyxncrex0',
  Title: 'How to Calculate APY Easily',
  Subtitle:
    "Learn to calculate APY in DeFi easily and maximize returns with Jumper Exchange's cross-chain liquidity tools. Learn to calculate APY in DeFi easily and maximize returns with Jumper Exchange's cross-chain liquidity tools. Learn to calculate APY in DeFi easily and maximize returns with Jumper Exchange's cross-chain liquidity tools",
  Slug: 'how-to-calculate-apy-easily',
  WordCount: 827,
  createdAt: '2024-09-20T07:39:46.450Z',
  updatedAt: '2026-03-17T12:29:15.100Z',
  Content: [
    {
      type: 'paragraph',
      children: [
        {
          text: 'Understanding how to calculate ',
          type: 'text',
        },
        {
          bold: true,
          text: 'Annual Percentage Yield (APY)',
          type: 'text',
        },
        {
          text: ' is crucial for maximizing returns on your investments in decentralized finance (DeFi). APY is a key metric used to measure the annualized return on an investment, taking into account the effects of compounding interest. In this guide, we’ll break down how to easily calculate APY, provide practical insights for DeFi investors, and explore how platforms like ',
          type: 'text',
        },
        {
          bold: true,
          text: 'Jumper Exchange',
          type: 'text',
        },
        {
          text: ' enhance your ability to optimize returns across different blockchains.',
          type: 'text',
        },
      ],
    },
    {
      type: 'paragraph',
      children: [
        {
          text: "Before diving into the calculations, it’s important to grasp the significance of APY in DeFi. Whether you're staking tokens, providing liquidity, or engaging in yield farming, knowing how to accurately calculate APY can help you make informed decisions about where to allocate your assets. For more information on optimizing your DeFi strategies, check out this ",
          type: 'text',
        },
        {
          url: 'https://medium.com/@thebinaryholdings/token-swapping-explained-what-is-it-and-how-can-you-benefit-7336c04d7315',
          type: 'link',
          children: [
            {
              text: 'guide to calculating APY in DeFi',
              type: 'text',
            },
          ],
        },
        {
          text: ' or explore how ',
          type: 'text',
        },
        {
          url: 'https://jumper.exchange/scan/',
          type: 'link',
          children: [
            {
              text: 'cross-chain liquidity aggregation',
              type: 'text',
            },
          ],
        },
        {
          text: ' can impact your returns.',
          type: 'text',
        },
      ],
    },
  ] as BlogArticleData['Content'],
  locale: 'en',
  localizations: { data: [] },
  Image: {
    id: '458',
    documentId: 'g407h7w6ufrt276jhrbezcjm',
    name: 'How to Calculate  APY Easily.jpg',
    alternativeText: undefined,
    caption: undefined,
    width: 1920,
    height: 1080,
    formats: {
      large: {
        ext: '.jpg',
        url: '/uploads/large_How_to_Calculate_APY_Easily_d61f8bd6c7.jpg',
        hash: 'large_How_to_Calculate_APY_Easily_d61f8bd6c7',
        mime: 'image/jpeg',
        name: 'large_How to Calculate  APY Easily.jpg',
        path: undefined,
        size: 45.38,
        width: 1000,
        height: 563,
      },
      small: {
        ext: '.jpg',
        url: '/uploads/small_How_to_Calculate_APY_Easily_d61f8bd6c7.jpg',
        hash: 'small_How_to_Calculate_APY_Easily_d61f8bd6c7',
        mime: 'image/jpeg',
        name: 'small_How to Calculate  APY Easily.jpg',
        path: undefined,
        size: 17.54,
        width: 500,
        height: 281,
      },
      medium: {
        ext: '.jpg',
        url: '/uploads/medium_How_to_Calculate_APY_Easily_d61f8bd6c7.jpg',
        hash: 'medium_How_to_Calculate_APY_Easily_d61f8bd6c7',
        mime: 'image/jpeg',
        name: 'medium_How to Calculate  APY Easily.jpg',
        path: undefined,
        size: 31.27,
        width: 750,
        height: 422,
      },
      thumbnail: {
        ext: '.jpg',
        url: '/uploads/thumbnail_How_to_Calculate_APY_Easily_d61f8bd6c7.jpg',
        hash: 'thumbnail_How_to_Calculate_APY_Easily_d61f8bd6c7',
        mime: 'image/jpeg',
        name: 'thumbnail_How to Calculate  APY Easily.jpg',
        path: undefined,
        size: 6.52,
        width: 245,
        height: 138,
      },
    },
    hash: 'How_to_Calculate_APY_Easily_d61f8bd6c7',
    ext: '.jpg',
    mime: 'image/jpeg',
    size: 119.21,
    url: '/uploads/How_to_Calculate_APY_Easily_d61f8bd6c7.jpg',
    previewUrl: undefined,
    provider: 'local',
    provider_metadata: null,
    createdAt: '2024-09-24T02:24:53.040Z',
    updatedAt: '2024-09-24T02:24:53.040Z',
  },
  tags: [
    {
      id: 1130,
      Title: 'Knowledge',
      Key: 'knowledge',
      createdAt: '2024-09-23T13:35:10.151Z',
      updatedAt: '2024-11-12T14:41:55.159Z',
      locale: 'en',
      documentId: 'furqjhighic63ifeojt17fmm',
      blog_articles: [],
    },
  ],
  author: {
    id: 2977,
    documentId: 'vtljyd6hq0uhmj4t1q5n43r2',
    Name: 'Marko Jurina',
    Role: 'CEO Jumper Exchange',
    Bio: undefined,
    Twitter: 'https://x.com/zord4n',
    LinkedIn: 'https://www.linkedin.com/in/markojurina/',
    createdAt: '2024-01-16T08:58:51.507Z',
    updatedAt: '2024-11-12T14:43:05.012Z',
    Avatar: {
      id: '43',
      documentId: 'nj50fcbofiu54l3ei2n7u7iu',
      name: 'marko-avatar.webp',
      alternativeText: undefined,
      caption: undefined,
      width: 240,
      height: 240,
      formats: {
        small: {
          ext: '.webp',
          url: '/uploads/marko_avatar_5117cebe77.webp',
          hash: 'marko_avatar_5117cebe77',
          mime: 'image/webp',
          name: 'marko-avatar.webp',
          path: undefined,
          size: 2.81,
          width: 240,
          height: 240,
        },
        medium: {
          ext: '.webp',
          url: '/uploads/marko_avatar_5117cebe77.webp',
          hash: 'marko_avatar_5117cebe77',
          mime: 'image/webp',
          name: 'marko-avatar.webp',
          path: undefined,
          size: 2.81,
          width: 240,
          height: 240,
        },
        large: {
          ext: '.webp',
          url: '/uploads/marko_avatar_5117cebe77.webp',
          hash: 'marko_avatar_5117cebe77',
          mime: 'image/webp',
          name: 'marko-avatar.webp',
          path: undefined,
          size: 2.81,
          width: 240,
          height: 240,
        },
        thumbnail: {
          ext: '.webp',
          url: '/uploads/thumbnail_marko_avatar_5117cebe77.webp',
          hash: 'thumbnail_marko_avatar_5117cebe77',
          mime: 'image/webp',
          name: 'thumbnail_marko-avatar.webp',
          path: undefined,
          size: 1.53,
          width: 156,
          height: 156,
        },
      },
      hash: 'marko_avatar_5117cebe77',
      ext: '.webp',
      mime: 'image/webp',
      size: 2.81,
      url: '/uploads/marko_avatar_5117cebe77.webp',
      previewUrl: undefined,
      provider: 'local',
      provider_metadata: null,
      createdAt: '2024-01-16T08:57:10.744Z',
      updatedAt: '2024-09-09T14:36:23.698Z',
    },
  },
  faq_items: [],
};
