name: Docker

on:
  push:
    branches: [ "main" ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
#   pull_request:
#     branches: [ "main", "develop" ]
  workflow_dispatch:

env:
  REGISTRY: 403372804574.dkr.ecr.us-east-2.amazonaws.com/lifi-docker-repo
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      docker-tag: ${{ steps.out.outputs.docker-tag }}
    permissions:
      id-token: write
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set current date as env variable
        run: echo "UNIQ_ID=$(date +'%y%m%d')-${GITHUB_SHA:0:7}" >> $GITHUB_ENV

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          role-to-assume: arn:aws:iam::403372804574:role/github-actions
          role-session-name: github-actions-role-session
          aws-region: us-east-2

      - name: Amazon ECR login
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=branch,prefix=${{ env.UNIQ_ID }}-

      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
           BUILD_ENV=${{env.BRANCH_NAME == 'main' && ' ' || format(':{0}',env.BRANCH_NAME) }}

      - id: out
        run: echo "docker-tag=${{ env.UNIQ_ID }}-${{ env.BRANCH_NAME }}" >> $GITHUB_OUTPUT
 ###########
  publish-tags:
    needs: build
    concurrency: charts/lifi-web/values.yaml
    runs-on: ubuntu-latest

    steps:
      - name: Checkout helm charts
        uses: actions/checkout@v3
        with:
          repository: lifinance/lifi-deployment
          ssh-key: ${{ secrets.DEPLOY_SSH }}
          ref: ${{ env.BRANCH_NAME }}
  
      - name: update image ID
        uses: mikefarah/yq@v4.28.2
        with:
          cmd: yq -i e '.image.tag |= "${{needs.build.outputs.docker-tag}}"' charts/lifi-web/${{ env.BRANCH_NAME }}-values.yaml

      - name: push image ID
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add charts/lifi-web/${{ env.BRANCH_NAME }}-values.yaml
          git commit -m "auto build version:${{needs.build.outputs.docker-tag}}"
          git push
