#!/bin/sh
if ! head -1 "$1" | grep -qE "^(Merge|feat|fix|ci|chore|docs|test|style|refactor|perf|build|revert|i18n)(\(.+?\))?: .{1,}$"; then
    echo "Aborting commit. Your commit message is invalid." >&2
    echo "It should start with: Merge|feat|fix|ci|chore|docs|test|style|refactor|perf|build|revert|i18n" >&2
    exit 1
fi
if ! head -1 "$1" | grep -qE "^.{1,88}$"; then
    echo "Aborting commit. Your commit message is too long." >&2
    exit 1
fi
