#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo "This is a Pre-Commit message as a placeholder for sripts/tests/hooks..."
# exit 1

# yarn pre-commit
yarn lint-staged;
yarn lerna run --concurrency 1 --stream precommit --since HEAD --exclude-dependents
