#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo "Executing pre-push scripts..."

npx lerna run fix:all-files && npx lerna run hook:prettier-test && npx lerna run hook:linter-test && npx lerna run hook:build-test && yarn pre-push || echo 'Push failed'
