#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo "Executing pre-push scripts..."

npx lerna exec -- yarn fix:all-files
npx lerna exec -- yarn hook:prettier
npx lerna exec -- yarn hook:linter
npx lerna exec -- yarn hook:build-check
yarn pre-push
