name: Build and push image

on:
  push:
    branches:
      - testnet
      - develop
      - staging
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      packages: write
    uses: lifinance/github-actions/.github/workflows/build-and-push-docker-with-args.yaml@main
    with:
      registry: 403372804574.dkr.ecr.us-east-2.amazonaws.com/lifi-docker-repo
      image-name: 'lifinance/jumper-exchange'
    secrets:
      deploy_key: ${{ secrets.DEPLOY_SSH }}