name: Deploy feature

on: pull_request

env:
  REGISTRY: 403372804574.dkr.ecr.us-east-2.amazonaws.com/lifi-docker-repo
  IMAGE_NAME: 'jumper-exchange'
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

jobs:
  debug:
    name: Debug wf
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
      pull-requests: write

    steps:
      - name: Checkout jumper-exchange
        uses: actions/checkout@v4

      - name: Set app name
        run: |
          NAME=$(echo "${{ env.BRANCH_NAME }}" | tr -d -c '[:alnum:]' | tr '[:upper:]' '[:lower:]')
          echo "APP_NAME=feat-${NAME:0:30}"
          echo "APP_NAME=feat-${NAME:0:30}" >> $GITHUB_ENV