name: Release

on:
  push:
    branches:
      - develop
      - LF-14162-3
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build-and-push:
    permissions:
      id-token: write
      contents: read
    uses: ./.github/workflows/build-and-push-multitag.yaml
    with:
      registry: europe-docker.pkg.dev/jumper-g-artifacts
      image-name: 'docker-jumper-exchange/jumpex'
      is-staging: false
      source-tag: ${{ github.ref_name }}
      commit-sha: ${{ github.sha }}
      ecr_repository: 'jumper-g-artifacts/docker-jumper-exchange/jumpex'
    secrets:
      deploy_key: ${{ secrets.DEPLOY_SSH }}
