on:
  pull_request:

env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write

    name: Publish to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Build App
        run: yarn install && yarn build

      - name: Deploy
        env:
          CLOUDFLARE_ACCOUNT_ID: secrets.CF_ACCOUNT_ID
          CLOUDFLARE_API_TOKEN: secrets.CF_PAGES_API_TOKEN
        run: |
          yarn install --dev wrangler
          npx wrangler pages deploy ./packages/dapp/dist/ --project-name test --branch ${{ env.BRANCH_NAME }}
